name: Generate Playground Assets

on: [ push ]

jobs:
  generate-playground-assets:
    runs-on: ubuntu-latest

    steps:

      - name: Clone phpdoc-parser source.
        uses: actions/checkout@v4
        with:
          repository: 'WordPress/phpdoc-parser'
          path: 'phpdoc-parser'

      - name: Change into phpdoc-parser directory.
        run: cd phpdoc-parser

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Configure Composer cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --working-dir "${{ github.workspace }}/phpdoc-parser"

      - name: Revert to previous directory.
        run: cd ..

      - name: Clone GatherPress sourcecode.
        uses: actions/checkout@v4
        with:
          repository: 'GatherPress/gatherpress'
          path: 'gatherpress'

      - name: Copy built assets into ZIP for extraction inside Playground.
        run: |
          mkdir -p assets/vendor
          mkdir -p assets/wp-content/uploads/gatherpress
          cp -r gatherpress/src assets/wp-content/uploads/gatherpress
          cp -r phpdoc-parser/vendor assets/vendor

      - name: Create downloadable artifact.
        uses: actions/upload-artifact@v4
        with:
          name: playground-assets
          path: assets
