name: Generate Playground Assets

on:
  workflow_dispatch:

jobs:
  generate-playground-assets:
    runs-on: ubuntu-latest

    steps:

      - name: Clone wporg-parent-2021 parent theme sourcecode.
        uses: actions/checkout@v4
        with:
          repository: 'WordPress/wporg-parent-2021'
          path: 'wporg-parent-2021'

      - name: Clone wporg-developer-2023 theme sourcecode.
        uses: actions/checkout@v4
        with:
          repository: 'WordPress/wporg-developer'
          path: 'wporg-developer-2023'

      - name: Clone GatherPress sourcecode.
        uses: actions/checkout@v4
        with:
          repository: 'GatherPress/gatherpress'
          path: 'gatherpress'

      - name: Clone phpdoc-parser source.
        uses: actions/checkout@v4
        with:
          repository: 'WordPress/phpdoc-parser'
          path: 'phpdoc-parser'

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Configure Composer cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --ignore-platform-req=php+ --working-dir "${{ github.workspace }}/phpdoc-parser"

      - name: Copy built assets into ZIP for extraction inside Playground.
        run: |
          mkdir -p wp-content/vendor
          mkdir -p wp-content/plugins/gatherpress
          mkdir -p wp-content/plugins/phpdoc-parser
          mkdir -p wp-content/themes/wporg-parent-2021
          mkdir -p wp-content/themes/wporg-developer-2023
          cp -r phpdoc-parser/vendor wp-content/vendor
          cp -r gatherpress wp-content/plugins/gatherpress
          cp -r phpdoc-parser wp-content/plugins/phpdoc-parser
          cp -r wporg-parent-2021/source/wp-content/themes/wporg-parent-2021 wp-content/themes/wporg-parent-2021
          cp -r wporg-developer-2023/source/wp-content/themes/wporg-developer-2023 wp-content/themes/wporg-developer-2023

      - name: Create downloadable artifact.
        uses: actions/upload-artifact@v4
        with:
          name: playground-assets
          path: assets
